import { Cliente } from "../modelo/cliente";

export const CLIENTES: Cliente[] = [
    {
      id: 1,
      nombre: 'Sergio',
      apellido: 'Mesa',
      email: 'sergio@correo.com',
      createAt: '2023/04/20',
    },
    {
      id: 2,
      nombre: 'Alisha',
      apellido: 'Allenby',
      email: 'aallenby1@edublogs.org',
      createAt: '2022-12-23',
    },
    {
      id: 3,
      nombre: 'Raimondo',
      apellido: 'Brothwell',
      email: 'rbrothwell2@alexa.com',
      createAt: '2022-12-05',
    },
    {
      id: 4,
      nombre: 'Taylor',
      apellido: 'Mackstead',
      email: 'tmackstead3@redcross.org',
      createAt: '2022-06-30',
    },
    {
      id: 5,
      nombre: 'Gabrielle',
      apellido: 'Fowler',
      email: 'gfowler4@spotify.com',
      createAt: '2022-10-01',
    },
    {
      id: 6,
      nombre: 'Sheila',
      apellido: 'Jesse',
      email: 'sjesse5@tripod.com',
      createAt: '2022-10-02',
    },
    {
      id: 7,
      nombre: 'Laryssa',
      apellido: 'Haggis',
      email: 'lhaggis6@ftc.gov',
      createAt: '2022-11-05',
    },
    {
      id: 8,
      nombre: 'Robinia',
      apellido: 'Roizn',
      email: 'rroizn7@jimdo.com',
      createAt: '2022-08-14',
    },
    {
      id: 9,
      nombre: 'Hazel',
      apellido: 'Oluwatoyin',
      email: 'holuwatoyin8@themeforest.net',
      createAt: '2022-07-26',
    },
    {
      id: 10,
      nombre: 'Cherianne',
      apellido: 'Doram',
      email: 'cdoram9@webmd.com',
      createAt: '2022-05-31',
    },
    {
      id: 11,
      nombre: 'Cicily',
      apellido: 'Blissett',
      email: 'cblissetta@ebay.co.uk',
      createAt: '2022-08-08',
    },
    {
      id: 12,
      nombre: 'Granthem',
      apellido: 'Follin',
      email: 'gfollinb@1und1.de',
      createAt: '2022-12-17',
    },
    {
      id: 13,
      nombre: 'Albina',
      apellido: 'Jumeau',
      email: 'ajumeauc@washington.edu',
      createAt: '2022-10-21',
    },
    {
      id: 14,
      nombre: 'Annamaria',
      apellido: 'Leare',
      email: 'aleared@disqus.com',
      createAt: '2022-09-21',
    },
    {
      id: 15,
      nombre: 'Tomas',
      apellido: 'Buckett',
      email: 'tbuckette@taobao.com',
      createAt: '2022-06-08',
    },
    {
      id: 16,
      nombre: 'Melisa',
      apellido: 'Bebbell',
      email: 'mbebbellf@acquirethisname.com',
      createAt: '2023-04-05',
    },
    {
      id: 17,
      nombre: 'Jaynell',
      apellido: 'Reuther',
      email: 'jreutherg@japanpost.jp',
      createAt: '2022-07-03',
    },
    {
      id: 18,
      nombre: 'Oliviero',
      apellido: 'Lindenstrauss',
      email: 'olindenstraussh@statcounter.com',
      createAt: '2022-05-15',
    },
    {
      id: 19,
      nombre: 'Wally',
      apellido: 'Tattoo',
      email: 'wtattooi@mashable.com',
      createAt: '2022-12-03',
    },
    {
      id: 20,
      nombre: 'Pippo',
      apellido: 'Dunsford',
      email: 'pdunsfordj@is.gd',
      createAt: '2022-11-10',
    },
    {
      id: 21,
      nombre: 'Siouxie',
      apellido: 'Casazza',
      email: 'scasazzak@goo.gl',
      createAt: '2022-06-01',
    },
    {
      id: 22,
      nombre: 'Coraline',
      apellido: 'Moreno',
      email: 'cmorenol@yellowpages.com',
      createAt: '2022-11-20',
    },
    {
      id: 23,
      nombre: 'Yasmin',
      apellido: 'Allans',
      email: 'yallansm@reverbnation.com',
      createAt: '2022-07-08',
    },
    {
      id: 24,
      nombre: 'Barnett',
      apellido: 'Blood',
      email: 'bbloodn@mozilla.org',
      createAt: '2022-09-15',
    },
    {
      id: 25,
      nombre: 'Tabbatha',
      apellido: 'Penney',
      email: 'tpenneyo@biglobe.ne.jp',
      createAt: '2022-09-25',
    },
    {
      id: 26,
      nombre: 'Gianna',
      apellido: 'Dach',
      email: 'gdachp@washington.edu',
      createAt: '2022-08-19',
    },
    {
      id: 27,
      nombre: 'Astrid',
      apellido: 'Driscoll',
      email: 'adriscollq@economist.com',
      createAt: '2022-05-26',
    },
    {
      id: 28,
      nombre: 'Nanny',
      apellido: 'Duffrie',
      email: 'nduffrier@creativecommons.org',
      createAt: '2022-07-16',
    },
    {
      id: 29,
      nombre: 'Kevin',
      apellido: 'Kolinsky',
      email: 'kkolinskys@census.gov',
      createAt: '2023-02-27',
    },
    {
      id: 30,
      nombre: 'Davy',
      apellido: 'Korejs',
      email: 'dkorejst@rakuten.co.jp',
      createAt: '2023-02-14',
    },
    {
      id: 31,
      nombre: 'Brenn',
      apellido: 'Eagland',
      email: 'beaglandu@noaa.gov',
      createAt: '2022-09-26',
    },
    {
      id: 32,
      nombre: 'Debera',
      apellido: 'Siemantel',
      email: 'dsiemantelv@nba.com',
      createAt: '2022-11-15',
    },
    {
      id: 33,
      nombre: 'Nigel',
      apellido: 'Ledes',
      email: 'nledesw@woothemes.com',
      createAt: '2022-07-20',
    },
    {
      id: 34,
      nombre: 'Dal',
      apellido: 'Moth',
      email: 'dmothx@cam.ac.uk',
      createAt: '2022-05-01',
    },
    {
      id: 35,
      nombre: 'Tab',
      apellido: 'Howarth',
      email: 'thowarthy@google.pl',
      createAt: '2022-12-22',
    },
    {
      id: 36,
      nombre: 'Berti',
      apellido: 'Campa',
      email: 'bcampaz@howstuffworks.com',
      createAt: '2022-07-10',
    },
    {
      id: 37,
      nombre: 'Almeria',
      apellido: 'Binnie',
      email: 'abinnie10@tmall.com',
      createAt: '2023-01-16',
    },
    {
      id: 38,
      nombre: 'Michaelina',
      apellido: 'De Rye Barrett',
      email: 'mderyebarrett11@sohu.com',
      createAt: '2022-12-16',
    },
    {
      id: 39,
      nombre: 'Kelcey',
      apellido: 'Engledow',
      email: 'kengledow12@symantec.com',
      createAt: '2022-07-15',
    },
    {
      id: 40,
      nombre: 'Marcellina',
      apellido: 'Ricciardelli',
      email: 'mricciardelli13@independent.co.uk',
      createAt: '2022-11-08',
    },
    {
      id: 41,
      nombre: 'Nance',
      apellido: 'Bulfit',
      email: 'nbulfit14@printfriendly.com',
      createAt: '2022-06-21',
    },
    {
      id: 42,
      nombre: 'Cassandre',
      apellido: 'Yapp',
      email: 'cyapp15@usatoday.com',
      createAt: '2022-11-11',
    },
    {
      id: 43,
      nombre: 'Jacquelyn',
      apellido: 'Kassidy',
      email: 'jkassidy16@harvard.edu',
      createAt: '2022-12-06',
    },
    {
      id: 44,
      nombre: 'Clement',
      apellido: 'Caghy',
      email: 'ccaghy17@ebay.com',
      createAt: '2022-12-02',
    },
    {
      id: 45,
      nombre: 'Genovera',
      apellido: 'Kennefick',
      email: 'gkennefick18@cdc.gov',
      createAt: '2022-06-15',
    },
    {
      id: 46,
      nombre: 'Nikolos',
      apellido: 'Cherm',
      email: 'ncherm19@phoca.cz',
      createAt: '2023-01-23',
    }, ];